<html>
  <head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery.ui.all.css"></link>
    <link rel="stylesheet" type="text/css" href="/css/site.css"></link>
    <!-- <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/dark-hive/jquery-ui.css"></link> -->
		<link rel="shortcut icon" href="../favicon.ico" type="image/x-icon"/>

  </head>
  <body>
<style type="text/css">

body{
	margin: 0;
	padding: 0;
	border: 0;
	overflow: hidden;
	height: 100%; 
	max-height: 100%; 
}	
</style>  
    {{> _header}}
	<div id="main">{{{main}}}</div>
    <div id="footer">{{> _footer}}</div>
	
	
  </body>
</html>
